#!/usr/bin/env node
/**
 * Derive audience-tailored EPK cuts from index.html (the single source of truth).
 *
 * index.html is authored once. Each variant in src/variants.json is generated by:
 *   1. keeping only the <main> sections whose data-audience contains "all" or the
 *      variant's audience token (everything else is dropped, in document order);
 *   2. dropping nav links (data-nav-for) that point at a dropped section;
 *   3. swapping the hero eyebrow/subcopy (data-slot) + the <head> SEO fields;
 *   4. optionally removing the budget ladder (hideBudgetLadder) and tagging the
 *      booking form with a hidden `variant` field + a per-cut email subject;
 *   5. rewriting root-relative asset/page links to absolute (/assets/…, /songs.html)
 *      so the page works from a subdirectory (/venues/) on any host.
 *
 * The result is written to <outDir>/index.html. The root full EPK is never touched.
 * Run via `npm run build` (this script, then the Tailwind purge over the output).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';

const root = dirname(fileURLToPath(import.meta.url));
const SRC = join(root, 'index.html');
const MANIFEST = join(root, 'src', 'variants.json');
const SITE = join(root, 'src', 'site.json');

const rawSource = readFileSync(SRC, 'utf8');
const { variants } = JSON.parse(readFileSync(MANIFEST, 'utf8'));

// Rewrite a single URL value to be root-absolute if it points at a local asset/page.
function absolutize(value) {
  if (!value) return value;
  // leave anchors, absolute URLs, already-rooted paths, and protocols alone
  if (/^(#|https?:|mailto:|tel:|\/|data:)/i.test(value)) return value;
  if (/^(assets\/|songs\.html|index\.html)/.test(value)) return '/' + value;
  return value;
}
// srcset / imagesrcset are comma-separated "url descriptor" lists
function absolutizeSrcset(value) {
  return value
    .split(',')
    .map((part) => {
      const seg = part.trim();
      const sp = seg.indexOf(' ');
      const url = sp === -1 ? seg : seg.slice(0, sp);
      const rest = sp === -1 ? '' : seg.slice(sp);
      return absolutize(url) + rest;
    })
    .join(', ');
}

function buildVariant(v) {
  const doc = parse(rawSource, { comment: true, blockTextElements: { script: true, style: true } });

  // 1. Section filter — keep sections tagged "all" or this variant's audience
  const kept = new Set();
  const removed = new Set();
  for (const section of doc.querySelectorAll('main > section')) {
    const tokens = (section.getAttribute('data-audience') || '').split(/\s+/).filter(Boolean);
    const keep = tokens.includes('all') || tokens.includes(v.audience);
    const id = section.getAttribute('id');
    if (keep) { if (id) kept.add(id); }
    else { if (id) removed.add(id); section.remove(); }
  }

  // 2. Drop nav links that point at a removed section
  for (const link of doc.querySelectorAll('[data-nav-for]')) {
    if (removed.has(link.getAttribute('data-nav-for'))) link.remove();
  }

  // 3a. Hero (and any) slot text overrides
  for (const [slot, htmlValue] of Object.entries(v.slots || {})) {
    const el = doc.querySelector(`[data-slot="${slot}"]`);
    if (el) el.set_content(htmlValue);
  }

  // 3b. <head> SEO overrides
  const setAttr = (sel, attr, val) => { const el = doc.querySelector(sel); if (el && val != null) el.setAttribute(attr, val); };
  const titleEl = doc.querySelector('title');
  if (titleEl && v.title) titleEl.set_content(v.title);
  setAttr('meta[name="description"]', 'content', v.description);
  setAttr('link[rel="canonical"]', 'href', v.canonical);
  setAttr('meta[property="og:url"]', 'content', v.ogUrl);
  setAttr('meta[property="og:title"]', 'content', v.ogTitle);
  setAttr('meta[property="og:description"]', 'content', v.ogDescription);
  setAttr('meta[name="twitter:title"]', 'content', v.ogTitle);
  setAttr('meta[name="twitter:description"]', 'content', v.ogDescription);

  // 4. Booking form: optional budget removal + variant tag + per-cut subject
  if (v.hideBudgetLadder) {
    const budget = doc.querySelector('[data-slot="budget-ladder"]');
    if (budget) budget.remove();
  }
  const form = doc.querySelector('#book form');
  if (form) {
    form.insertAdjacentHTML('afterbegin', `\n              <input type="hidden" name="variant" value="${v.slug}">`);
    const subject = form.querySelector('input[name="_subject"]');
    if (subject && v.subjectLabel) subject.setAttribute('value', `New booking inquiry (${v.subjectLabel}) — Chris Zemba EPK`);
  }

  // 5. Root-absolutize local asset/page references so /venues/ resolves correctly
  for (const el of doc.querySelectorAll('*')) {
    for (const attr of ['src', 'href', 'data-src', 'poster']) {
      const val = el.getAttribute(attr);
      if (val != null) { const abs = absolutize(val); if (abs !== val) el.setAttribute(attr, abs); }
    }
    for (const attr of ['srcset', 'imagesrcset']) {
      const val = el.getAttribute(attr);
      if (val != null) { const abs = absolutizeSrcset(val); if (abs !== val) el.setAttribute(attr, abs); }
    }
    // inline logo fallback handler: onerror="this.src='assets/…'"
    const onerror = el.getAttribute('onerror');
    if (onerror && onerror.includes("this.src='assets/")) {
      el.setAttribute('onerror', onerror.replace("this.src='assets/", "this.src='/assets/"));
    }
  }

  let out = doc.toString();
  if (!/^\s*<!doctype/i.test(out)) out = '<!doctype html>\n' + out;

  const outPath = join(root, v.outDir, 'index.html');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out);
  return { outPath, kept: [...kept], removed: [...removed] };
}

let ok = 0;
for (const v of variants) {
  const r = buildVariant(v);
  console.log(`built ${v.outDir}/index.html — kept [${r.kept.join(', ')}] · dropped [${r.removed.join(', ')}]`);
  ok++;
}

// Emit /epk.json — a public, machine-readable manifest of booking contact details, the venue-cut
// URL, and downloadable asset links. The Setlist-Generator venue-outreach app fetches this to sync
// its EPK settings, so the two projects share one source of truth and never drift. Only the
// already-public data in src/site.json is exposed here.
const site = JSON.parse(readFileSync(SITE, 'utf8'));
delete site._comment;
writeFileSync(join(root, 'epk.json'), JSON.stringify({ ...site, updatedAt: new Date().toISOString() }, null, 2) + '\n');
console.log('wrote epk.json (public sync manifest)');

console.log(`\n${ok} variant(s) generated from index.html.`);
