#!/usr/bin/env node
/**
 * Sync Bandsintown events → MusicEvent JSON-LD baked into index.html (the single source of truth).
 *
 * The on-page Bandsintown widget renders events client-side, so search engines don't index them.
 * This script fetches the SAME events from the Bandsintown REST API (server-side, no CORS problem)
 * and writes schema.org `MusicEvent` structured data into the delimited block in index.html, so the
 * act's real upcoming shows become eligible for Google event rich results. `npm run build` then
 * propagates that block into every generated cut (they inherit index.html's <head>).
 *
 * Run by .github/workflows/sync-events.yml on a daily cron. Resilient by design: any fetch/parse
 * failure leaves the last-good block untouched and exits 0, so a transient API blip never blanks the
 * schema or breaks the build. Only rewrites index.html when the event data actually changed.
 *
 * The app_id is the PUBLIC Bandsintown widget/app identifier (already in index.html as data-app-id) —
 * not a secret. Override via env if ever needed.
 *
 * No third-party deps: native fetch (Node ≥18) + string replacement.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'index.html');

const ARTIST_ID = process.env.BIT_ARTIST_ID || 'id_14646019';
const APP_ID = process.env.BIT_APP_ID || '3e4eac79fcd71e8e2e0a45643fe1c75a';
const ARTIST_NAME = process.env.BIT_ARTIST_NAME || 'Chris Zemba';
const ORG_ID = 'https://zembamusicco.com/#org';

const START = '<!-- BIT-EVENTS-JSONLD:START';
const END = 'BIT-EVENTS-JSONLD:END -->';

/**
 * Pure transform: Bandsintown event objects → an array of schema.org MusicEvent objects.
 * Kept dependency-free and side-effect-free so it is unit-testable headlessly.
 * @param {Array<object>} events  raw Bandsintown /events payload
 * @returns {Array<object>} MusicEvent JSON-LD nodes
 */
export function eventsToMusicEvents(events) {
  if (!Array.isArray(events)) return [];
  return events
    .filter((e) => e && e.datetime)
    .map((e) => {
      const v = e.venue || {};
      const node = {
        '@context': 'https://schema.org',
        '@type': 'MusicEvent',
        name: (e.title && e.title.trim()) || `${ARTIST_NAME} at ${v.name || 'a live show'}`,
        startDate: e.datetime,
        eventStatus: 'https://schema.org/EventScheduled',
        eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
        performer: { '@type': 'MusicGroup', name: ARTIST_NAME, '@id': ORG_ID },
        organizer: { '@type': 'Organization', name: 'Zemba Music Co', '@id': ORG_ID },
      };

      const place = { '@type': 'Place' };
      if (v.name) place.name = v.name;
      const address = { '@type': 'PostalAddress' };
      if (v.city) address.addressLocality = v.city;
      if (v.region) address.addressRegion = v.region;
      if (v.country) address.addressCountry = v.country;
      if (Object.keys(address).length > 1) place.address = address;
      if (v.latitude && v.longitude) {
        place.geo = { '@type': 'GeoCoordinates', latitude: v.latitude, longitude: v.longitude };
      }
      if (Object.keys(place).length > 1) node.location = place;

      if (e.url) node.url = e.url;

      // Ticket/RSVP offers → schema Offer (url only; never invent a price).
      const offers = (Array.isArray(e.offers) ? e.offers : [])
        .filter((o) => o && o.url)
        .map((o) => {
          const offer = { '@type': 'Offer', url: o.url, availability: 'https://schema.org/InStock' };
          if (/rsvp/i.test(o.type || '')) offer.price = '0';
          return offer;
        });
      if (offers.length) node.offers = offers.length === 1 ? offers[0] : offers;

      return node;
    });
}

/** Serialize for safe embedding inside an HTML <script> (neutralize `<` so `</script>`/`<!--` can't break out). */
export function serializeJsonLd(nodes) {
  return JSON.stringify(nodes, null, 2).replace(/</g, '\\u003c');
}

/** Replace the content of the delimited JSON-LD block. Returns the new HTML, or null if markers missing. */
export function injectBlock(html, jsonLd) {
  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return null;
  const blockEnd = endIdx + END.length;
  const replacement =
    `${START} — auto-generated by scripts/sync-events.mjs from the Bandsintown\n` +
    `       Events API (artist ${ARTIST_ID}). Do NOT hand-edit; the daily GitHub Action overwrites the\n` +
    `       array below with real upcoming shows so they're eligible for Google event rich results.\n` +
    `       Empty [] is valid and harmless when there are no upcoming dates. -->\n` +
    `  <script type="application/ld+json" id="bit-events-jsonld">${jsonLd}</script>\n` +
    `  <!-- ${END}`;
  return html.slice(0, startIdx) + replacement + html.slice(blockEnd);
}

async function main() {
  const url = `https://rest.bandsintown.com/artists/${encodeURIComponent(ARTIST_ID)}/events?app_id=${encodeURIComponent(APP_ID)}&date=upcoming`;
  let raw;
  try {
    const res = await fetch(url, { headers: { Accept: 'application/json' } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    raw = await res.json();
  } catch (err) {
    console.error(`sync-events: fetch failed (${err.message}); leaving existing JSON-LD untouched.`);
    process.exit(0); // resilient: never blank the schema or fail the build on a transient error
  }
  if (!Array.isArray(raw)) {
    console.error('sync-events: unexpected payload (not an array); leaving existing JSON-LD untouched.');
    process.exit(0);
  }

  const nodes = eventsToMusicEvents(raw);
  const jsonLd = serializeJsonLd(nodes);

  const html = readFileSync(INDEX, 'utf8');
  const next = injectBlock(html, jsonLd);
  if (next === null) {
    console.error('sync-events: BIT-EVENTS-JSONLD markers not found in index.html; nothing written.');
    process.exit(1);
  }
  if (next === html) {
    console.log(`sync-events: ${nodes.length} event(s); no change.`);
    return;
  }
  writeFileSync(INDEX, next);
  console.log(`sync-events: wrote ${nodes.length} MusicEvent node(s) into index.html.`);
}

// Only run the network path when executed directly (keeps the exports importable for tests).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
